### ISSUE TITLE
画面のカンプ・プロトタイプ

### ISSUE THREAD

**Issue by hiracky16** [ebc0729/RailsRec#1]
スマホサイズの画面での画面のイメージを作成

Weex 側で調査してほしいことをまとめたシート
https://docs.google.com/spreadsheets/d/1znJCHi8s5j7qYhEROcc0O5fOxDeSPIrabmq5gjFHWr0/edit#gid=233119613&range=A1

**Comment by hiracky16** [comment]
@pyoshifuji カンプとプロトタイプの作成お願いします。
一旦期限は2週間後を設定しています。

**Comment by hiracky16** [comment]
@pyoshifuji 静的実装は別イシューで対応してもらおうと考えていました。
デザインカンプと Xd でのイメージ作成だとどのくらい掛かりそうですか？

**Comment by pyoshifuji** [comment]
なるほど！別に工数撮っていただけるなら、カンプとプロトタイプで2週でいけそうです。了解しました。

**Comment by hiracky16** [comment]
@pyoshifuji デザイン上、必要なアニメーションがあり、それが実装可能かは #2 で調査します。
以下のシートに調査内容を記述していただければと思います。

調査シート
https://docs.google.com/spreadsheets/d/1znJCHi8s5j7qYhEROcc0O5fOxDeSPIrabmq5gjFHWr0/edit#gid=233119613&range=A1

@morinokumakamesan

**Comment by pyoshifuji** [comment]
@hiracky16 

作成完了しました。ご確認ください。

プロトタイプ
https://xd.adobe.com/view/ba0166c4-1d48-41f1-681f-2ecd5202695b-cc30/

ファイル
https://drive.google.com/drive/folders/15UgWxK31msoSAIy5uONO-k7n1eJuGA47

**Comment by hiracky16** [comment]
デザインは完成したためクローズ。
@pyoshifuji
